# Generated by Django 5.1.1 on 2024-10-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_workexperience_alter_coursework_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
